---
abstract: 'provide some ways to leave messages when script died'
author:
  - 'Ktat <ktat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Script-Carp
no_index:
  directory:
    - t
    - inc
requires:
  IO::Scalar: 0
  Test::More: 0
version: 0.05
